# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='random_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
