# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bookmark_random_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click',
            name='clicked',
        ),
    ]
